name: Parallel jobs
on: [push]

jobs:
  stage1:
    name: Stage 1
    runs-on: ubuntu-latest

    steps:
    - name: Sleep and Run
      run: |
        echo "Sleeping for 10"
        sleep 10

  stage2a:
    name: Stage 2a
    runs-on: ubuntu-latest
    needs: stage1

    steps:
      - name: Sleep and Run
        run: |
          echo "Sleeping for 10"
          sleep 10

  stage2b:
    name: Stage 2b
    runs-on: ubuntu-latest
    needs: stage1

    steps:
      - name: Sleep and Run
        run: |
          echo "Sleeping for 10"
          sleep 10

  stage2c:
    name: Stage 2c
    runs-on: ubuntu-latest
    needs: stage1

    steps:
      - name: Sleep and Run
        run: |
          echo "Sleeping for 10"
          sleep 10

  stage3:
    name: Stage 3
    runs-on: ubuntu-latest
    needs: [stage2a, stage2b, stage2c]

    steps:
      - name: Sleep and Run
        run: |
          echo "Sleeping for 10"
          sleep 10